import "../styles/globals.css";
import Head from "next/head";

import "@rainbow-me/rainbowkit/styles.css";
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import {
  chain,
  configureChains,
  createClient,
  WagmiConfig,
  useSigner,
  useContract,
} from "wagmi";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";
import ABI from "../utils/ABI.json";

const { chains, provider } = configureChains(
  [chain.goerli, chain.polygon],
  [alchemyProvider({ apiKey: process.env.ALCHEMY_ID }), publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "La Vaca web3",
  chains,
});
const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});

function MyApp({ Component, pageProps }) {
  const contract = useContract({
    addressOrName: "0xAfDdCE9E0cA4f63dD32e7733Aead3573C9721aF4",
    contractInterface: ABI,
  });
  // console.log("🚀 ~ file: _app.js ~ line 32 ~ MyApp ~ contract", contract);
  // console.log("🚀 ~ file: _app.js ~ line 32 ~ MyApp ~ ABI", ABI);

  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <Head>
          <title>VACAWEB3</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
